#!/usr/bin/env python3
"""
Generate simple STL geometry files for SPH fluid simulation development.
Creates a 1cm box and 1cm sphere in binary STL format.
"""

import struct
import math
import os

def write_stl_header(f, num_triangles):
    """Write 80-byte header and triangle count."""
    header = b"Generated by ultraballpit geometry generator" + b"\x00" * 36
    f.write(header)
    f.write(struct.pack('<I', num_triangles))

def write_triangle(f, normal, v1, v2, v3):
    """Write a single triangle to binary STL file."""
    # Normal vector
    f.write(struct.pack('<fff', *normal))
    # Vertices
    f.write(struct.pack('<fff', *v1))
    f.write(struct.pack('<fff', *v2))
    f.write(struct.pack('<fff', *v3))
    # Attribute byte count (unused)
    f.write(struct.pack('<H', 0))

def compute_normal(v1, v2, v3):
    """Compute unit normal vector using right-hand rule."""
    # Edge vectors
    e1 = [v2[i] - v1[i] for i in range(3)]
    e2 = [v3[i] - v1[i] for i in range(3)]

    # Cross product
    n = [
        e1[1] * e2[2] - e1[2] * e2[1],
        e1[2] * e2[0] - e1[0] * e2[2],
        e1[0] * e2[1] - e1[1] * e2[0]
    ]

    # Normalize
    length = math.sqrt(sum(x*x for x in n))
    if length > 0:
        n = [x / length for x in n]

    return tuple(n)

def generate_box_stl(filepath):
    """Generate a 1cm cube (0.01m edges) centered at origin."""
    half = 0.005  # 0.5cm = 0.005m

    # 8 corners of the cube
    corners = [
        (-half, -half, -half),  # 0
        ( half, -half, -half),  # 1
        ( half,  half, -half),  # 2
        (-half,  half, -half),  # 3
        (-half, -half,  half),  # 4
        ( half, -half,  half),  # 5
        ( half,  half,  half),  # 6
        (-half,  half,  half),  # 7
    ]

    # 12 triangles (2 per face, 6 faces)
    # Each face is split into 2 triangles with counter-clockwise winding (outward normals)
    faces = [
        # Front face (z = -half, normal points -z)
        (0, 2, 1), (0, 3, 2),
        # Back face (z = +half, normal points +z)
        (4, 6, 7), (4, 5, 6),
        # Left face (x = -half, normal points -x)
        (0, 7, 3), (0, 4, 7),
        # Right face (x = +half, normal points +x)
        (1, 6, 5), (1, 2, 6),
        # Bottom face (y = -half, normal points -y)
        (0, 5, 4), (0, 1, 5),
        # Top face (y = +half, normal points +y)
        (3, 6, 2), (3, 7, 6),
    ]

    with open(filepath, 'wb') as f:
        write_stl_header(f, len(faces))

        for face in faces:
            v1, v2, v3 = corners[face[0]], corners[face[1]], corners[face[2]]
            normal = compute_normal(v1, v2, v3)
            write_triangle(f, normal, v1, v2, v3)

    print(f"✓ Generated {filepath} ({len(faces)} triangles)")

def generate_sphere_stl(filepath):
    """Generate a 1cm diameter sphere using icosphere subdivision."""
    radius = 0.005  # 0.5cm = 0.005m

    # Start with icosahedron vertices
    phi = (1.0 + math.sqrt(5.0)) / 2.0  # Golden ratio

    # Normalize to unit sphere
    a = 1.0 / math.sqrt(1.0 + phi * phi)
    b = phi * a

    vertices = [
        (-a,  b,  0), ( a,  b,  0), (-a, -b,  0), ( a, -b,  0),
        ( 0, -a,  b), ( 0,  a,  b), ( 0, -a, -b), ( 0,  a, -b),
        ( b,  0, -a), ( b,  0,  a), (-b,  0, -a), (-b,  0,  a),
    ]

    # Icosahedron faces
    faces = [
        (0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
        (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
        (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
        (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1),
    ]

    # Subdivide once for smoother sphere (20 -> 80 triangles)
    def subdivide(vertices, faces):
        """Subdivide each triangle into 4 smaller triangles."""
        new_faces = []
        edge_map = {}

        def get_midpoint(i1, i2):
            """Get or create midpoint vertex."""
            key = tuple(sorted([i1, i2]))
            if key in edge_map:
                return edge_map[key]

            v1, v2 = vertices[i1], vertices[i2]
            mid = tuple((v1[i] + v2[i]) / 2.0 for i in range(3))

            # Normalize to unit sphere
            length = math.sqrt(sum(x*x for x in mid))
            mid = tuple(x / length for x in mid)

            vertices.append(mid)
            edge_map[key] = len(vertices) - 1
            return edge_map[key]

        for face in faces:
            v0, v1, v2 = face

            # Get midpoint indices
            m01 = get_midpoint(v0, v1)
            m12 = get_midpoint(v1, v2)
            m20 = get_midpoint(v2, v0)

            # Create 4 new triangles
            new_faces.append((v0, m01, m20))
            new_faces.append((v1, m12, m01))
            new_faces.append((v2, m20, m12))
            new_faces.append((m01, m12, m20))

        return new_faces

    # Subdivide once
    vertices = list(vertices)
    faces = subdivide(vertices, faces)

    # Scale to desired radius
    vertices = [tuple(x * radius for x in v) for v in vertices]

    with open(filepath, 'wb') as f:
        write_stl_header(f, len(faces))

        for face in faces:
            v1, v2, v3 = vertices[face[0]], vertices[face[1]], vertices[face[2]]
            normal = compute_normal(v1, v2, v3)
            write_triangle(f, normal, v1, v2, v3)

    print(f"✓ Generated {filepath} ({len(faces)} triangles)")

def verify_stl(filepath):
    """Verify STL file has correct format."""
    actual_size = os.path.getsize(filepath)

    with open(filepath, 'rb') as f:
        # Read header
        header = f.read(80)

        # Read triangle count
        count_bytes = f.read(4)
        if len(count_bytes) != 4:
            return False

        triangle_count = struct.unpack('<I', count_bytes)[0]

        # Check file size
        expected_size = 80 + 4 + (triangle_count * 50)

        if expected_size != actual_size:
            print(f"  Warning: Expected {expected_size} bytes, got {actual_size}")
            return False

        print(f"  ✓ Valid STL: {triangle_count} triangles, {actual_size} bytes")
        return True

def main():
    # Create geometries directory
    geometries_dir = '/Users/tim/ai-twin/ultraballpit/geometries'
    os.makedirs(geometries_dir, exist_ok=True)

    # Generate STL files
    box_path = os.path.join(geometries_dir, 'box-1cm.stl')
    sphere_path = os.path.join(geometries_dir, 'sphere-1cm.stl')

    print("Generating geometry files...")
    generate_box_stl(box_path)
    verify_stl(box_path)

    generate_sphere_stl(sphere_path)
    verify_stl(sphere_path)

    print("\nDone! Geometry files created in geometries/")

if __name__ == '__main__':
    main()
